### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by sebdumancic** [Herb-AI/HerbBenchmarks.jl#6]
@Sebastijan, add all the links

**Comment by sebdumancic** [comment]
- make a repo per problem?

**Comment by THinnerichs** [comment]
Add https://github.com/SyGuS-Org/benchmarks and other benchmarks from the SyGuS-Comp to the repo

**Comment by ReubenJ** [comment]
We've since opened issues per-problem. Closing this in favor of that pattern.
